In [4]:
x = (1,2.0)

In [5]:
x

(1, 2.0)

In [6]:
x[0]

1

In [7]:
x[1]

2.0

In [8]:
x[0] = 'a'

TypeError: 'tuple' object does not support item assignment

In [9]:
x = (3,2.0)

In [10]:
x

(3, 2.0)

In [11]:
x = [3,2.0]

In [12]:
x

[3, 2.0]

In [13]:
type(x)

list

In [14]:
x[0] = 'a'

In [15]:
x

['a', 2.0]

In [16]:
y = x

In [17]:
y

['a', 2.0]

In [18]:
x

['a', 2.0]

In [19]:
y[0] = -99

In [20]:
y

[-99, 2.0]

In [21]:
x

[-99, 2.0]

In [22]:
y = x[:]

In [23]:
y

[-99, 2.0]

In [24]:
x

[-99, 2.0]

In [25]:
y[0] = 0

In [26]:
y

[0, 2.0]

In [27]:
x

[-99, 2.0]

In [28]:
x = [3.14 2.71 1.61 0 1 1.57 1.41 1.73]

SyntaxError: invalid syntax (<ipython-input-28-a24a34d32b2c>, line 1)

In [29]:
x = [3.14,2.71,1.61,0,1,1.57,1.41,1.73]

In [30]:
del x

In [31]:
x

NameError: name 'x' is not defined

In [32]:
x = [3.14,2.71,1.61,0,1,1.57,1.41,1.73]

In [33]:
x

[3.14, 2.71, 1.61, 0, 1, 1.57, 1.41, 1.73]

In [34]:
x = ''

In [35]:
x

''

In [36]:
x = None

In [37]:
x = [3.14,2.71,1.61,0,1,1.57,1.41,1.73]

In [38]:
len(x)

8

In [39]:
x[0:4:1]

[3.14, 2.71, 1.61, 0]

In [40]:
x[:4]

[3.14, 2.71, 1.61, 0]

In [41]:
x[4:]

[1, 1.57, 1.41, 1.73]

In [42]:
x[4:8:1]

[1, 1.57, 1.41, 1.73]

In [43]:
x[4::]

[1, 1.57, 1.41, 1.73]

In [44]:
x[::2]

[3.14, 1.61, 1, 1.41]

In [45]:
x

[3.14, 2.71, 1.61, 0, 1, 1.57, 1.41, 1.73]

In [46]:
x[2::2]

[1.61, 1, 1.41]

In [47]:
x[1::2]

[2.71, 0, 1.57, 1.73]

In [48]:
len(x)/2

4

In [49]:
len(x)//2

4

In [50]:
int(len(x)/2)

4

In [51]:
complex(len(x)/2)

(4+0j)

In [52]:
x[-1]

1.73

In [53]:
x

[3.14, 2.71, 1.61, 0, 1, 1.57, 1.41, 1.73]

In [54]:
x[-2]

1.41

In [55]:
x[-8]

3.14

In [56]:
x[-16]

IndexError: list index out of range

In [57]:
x[len(x)-1]

1.73

In [58]:
x[::-1]

[1.73, 1.41, 1.57, 1, 0, 1.61, 2.71, 3.14]

In [59]:
x

[3.14, 2.71, 1.61, 0, 1, 1.57, 1.41, 1.73]

In [60]:
x

[3.14, 2.71, 1.61, 0, 1, 1.57, 1.41, 1.73]

In [61]:
y = x[:]

In [62]:
import copy

In [63]:
y = copy.deepcopy(x)

In [64]:
y

[3.14, 2.71, 1.61, 0, 1, 1.57, 1.41, 1.73]

In [65]:
y[0] = 'python'

In [66]:
y

['python', 2.71, 1.61, 0, 1, 1.57, 1.41, 1.73]

In [68]:
x = [0,1]

In [69]:
y = list((0,1))

In [70]:
y

[0, 1]

In [71]:
type(y)

list

In [72]:
z = []

In [73]:
z

[]

In [74]:
float('123')

123.0

In [75]:
type(z)

list

In [76]:
z.append(1)

In [77]:
z

[1]

In [78]:
z.append(1)

In [79]:
z

[1, 1]

In [80]:
z.append(1)

In [81]:
z

[1, 1, 1]

In [82]:
z.insert(0,'a')

In [83]:
z

['a', 1, 1, 1]

In [84]:
z.insert(1,'b')

In [85]:
z

['a', 'b', 1, 1, 1]

In [86]:
z.pop(1)

'b'

In [87]:
z

['a', 1, 1, 1]

In [88]:
z.remove(1)

In [89]:
z

['a', 1, 1]

In [90]:
z.remove('b')

ValueError: list.remove(x): x not in list

In [91]:
x=[[0,1,0],[45,.7071,.7071],[90,.5,.866],[135,-.7071,.7071]]

In [92]:
x

[[0, 1, 0], [45, 0.7071, 0.7071], [90, 0.5, 0.866], [135, -0.7071, 0.7071]]

In [93]:
x=[[0,1,0,'a',None],[45,.7071,.7071],[90,.5,.866],[135,-.7071,.7071]]

In [94]:
x

[[0, 1, 0, 'a', None],
 [45, 0.7071, 0.7071],
 [90, 0.5, 0.866],
 [135, -0.7071, 0.7071]]

In [95]:
x[0]

[0, 1, 0, 'a', None]

In [96]:
y = x[0]

In [97]:
y[0]

0

In [98]:
y[1]

1

In [99]:
y[-1]

In [100]:
y[-2]

'a'

In [101]:
y[-1] = -1

In [102]:
y[-2] = -2

In [103]:
y

[0, 1, 0, -2, -1]

In [104]:
x

[[0, 1, 0, -2, -1],
 [45, 0.7071, 0.7071],
 [90, 0.5, 0.866],
 [135, -0.7071, 0.7071]]

In [105]:
x=[[0,1,0,'a',None],[45,.7071,.7071],[90,.5,.866],[135,-.7071,.7071]]

In [106]:
x

[[0, 1, 0, 'a', None],
 [45, 0.7071, 0.7071],
 [90, 0.5, 0.866],
 [135, -0.7071, 0.7071]]

In [107]:
x[0][-1]

In [108]:
x[0][-1] = -1

In [109]:
x[0][-2] = -2

In [110]:
x

[[0, 1, 0, -2, -1],
 [45, 0.7071, 0.7071],
 [90, 0.5, 0.866],
 [135, -0.7071, 0.7071]]

In [111]:
x[:2]

[[0, 1, 0, -2, -1], [45, 0.7071, 0.7071]]

In [112]:
x[:1]

[[0, 1, 0, -2, -1]]

In [113]:
x[1]

[45, 0.7071, 0.7071]

In [114]:
x[0]

[0, 1, 0, -2, -1]

In [115]:
x[:1]

[[0, 1, 0, -2, -1]]

In [116]:
x[:1][0]

[0, 1, 0, -2, -1]

In [117]:
x[0][0]

0

In [118]:
import copy

In [119]:
x

[[0, 1, 0, -2, -1],
 [45, 0.7071, 0.7071],
 [90, 0.5, 0.866],
 [135, -0.7071, 0.7071]]

In [120]:
y=x

In [121]:
y=x[:]

In [122]:
y[0][0]=-99

In [123]:
y

[[-99, 1, 0, -2, -1],
 [45, 0.7071, 0.7071],
 [90, 0.5, 0.866],
 [135, -0.7071, 0.7071]]

In [124]:
x

[[-99, 1, 0, -2, -1],
 [45, 0.7071, 0.7071],
 [90, 0.5, 0.866],
 [135, -0.7071, 0.7071]]

In [ ]:
y = copy.deepcopy(x)

In [ ]:
y

In [ ]:
x

In [ ]:
y[0][0]=3.14

In [ ]:
y

In [ ]:
x

In [ ]:
x

In [ ]:
x[1::2]

In [ ]:
x

In [ ]:
x[0]

In [ ]:
x[0]

In [ ]:
z = x[0][:]

In [ ]:
z

In [ ]:
x

In [ ]:
x[0]

In [ ]:
z

In [ ]:
z[0] = -1

In [ ]:
x[0]

In [ ]:
z

In [ ]:
z = copy.deepcopy(x[0])

In [ ]:
z = copy.deepcopy(x)[0]

In [ ]:
z = copy.deepcopy(x)

In [ ]:
z = z[0]

In [ ]:
z = x[0][:]

In [ ]:
%timeit z = x[0][:]

In [ ]:
%timeit z = copy.deepcopy(x)[0]

In [ ]:
%timeit z = copy.deepcopy(x[0])

In [ ]:
ex = 'Python is an interesting and useful language'

In [ ]:
ex = 'Python is an interesting and useful language fo rnumerical computing'

In [ ]:
ex = 'Python is an interesting and useful language for numerical computing'

In [ ]:
ex[:10]

In [ ]:
ex[:10] = 'aabbccddee'

In [ ]:
d = {}

In [ ]:
type(d)

In [ ]:
d

In [ ]:
d = {'a':1,'b':'f','c':3.14}

In [ ]:
d

In [ ]:
d['a']

In [ ]:
d['b']

In [ ]:
d = dict(a=1,b='b',c=3.14)

In [ ]:
d

In [ ]:
d = dict(a=1,b='b',a=3.14)

In [ ]:
d

In [ ]:
d['a']= 1.61

In [ ]:
d

In [ ]:
d['d']= 2.71

In [ ]:
d

In [ ]:
d['e']

In [ ]:
d.has_key('e')

In [ ]:
d.keys()

In [ ]:
del d['d']

In [ ]:
d

In [ ]:
d.keys()

In [ ]:
d.keys()[-1]

In [ ]:
d[d.keys()[-1]]

In [ ]:
del d[d.keys()[-1]]

In [ ]:
del d[d.keys()[-1]]

In [ ]:
del d[d.keys()[-1]]

In [ ]:
d

In [ ]:
array([3,2,1])

In [ ]:
x = array([3,2,1])

In [ ]:
x

In [ ]:
x = array((3,2,1))

In [ ]:
x

In [ ]:
x.ndim

In [ ]:
import numpy as np

In [ ]:
x = np.array([3,2,1])

In [ ]:
from numpy import array

In [ ]:
array([3,2,1])

In [ ]:
x.ndim

In [ ]:
array([[3,2,1]])

In [ ]:
x = array([[3,2,1]])

In [ ]:
x.ndim

In [ ]:
x

In [ ]:
x.shape

In [ ]:
x = np.array([3,2,1])

In [ ]:
x.shape

In [ ]:
(3L)

In [ ]:
(3L,)

In [ ]:
y = array([[9,8,7]])

In [ ]:
y

In [ ]:
y.shape

In [ ]:
y = array([[9],[8],[7]])

In [ ]:
y

In [ ]:
z = array([9,8,7])

In [ ]:
z

In [ ]:
z.T

In [ ]:
z = array([[9,8,7]])

In [ ]:
z.T

In [ ]:
z

In [ ]:
w = array([9,8,7])

In [ ]:
w

In [ ]:
w.ndim

In [ ]:
w

In [ ]:
w.T

In [ ]:
z = array([[3.1,3.4,3.7],[3.2,3.5,3.8],[3,3,3.6,3.9]])

In [ ]:
z

In [ ]:
z = array([[3.1,3.4,3.7],[3.2,3.5,3.8],[3.3,3.6,3.9]])

In [ ]:
z

In [ ]:
z.ndim

In [ ]:
z.shape

In [ ]:
z

In [ ]:
x

In [ ]:
array([x])

In [ ]:
array([x,x,x])

In [ ]:
z

In [ ]:
t = [z,z]

In [ ]:
t

In [ ]:
t = array([z,z])

In [ ]:
t

In [ ]:
t.ndim

In [ ]:
a = array(1,2,3)

In [ ]:
a = array([1,2,3])

In [ ]:
a

In [ ]:
a.dtype

In [ ]:
a = array([1,2,3],dtype='float64')

In [ ]:
a = array([1,2,3],dtype='float')

In [ ]:
a = array([1,2,3],dtype='complex')

In [ ]:
a = array([1,2,3],dtype='complex128')

In [ ]:
a

In [ ]:
a

In [ ]:
a * a

In [ ]:
r = matrix(x)

In [ ]:
r

In [ ]:
x

In [ ]:
r.ndim

In [ ]:
x*x

In [ ]:
r*r

In [ ]:
r.T*r

In [ ]:
r*r.T

In [ ]:
x = array([x])

In [ ]:
x

In [ ]:
x * x

In [ ]:
%hist?

In [ ]:
%notebook?

In [ ]:
cd c:\temp

In [ ]:
%notebook?

In [ ]:
%notebook -e -f py class3.py